site_name: Tunnel
plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
        - scripts/gen_readme_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            members_order: source
            separate_signature: true
            signature_crossrefs: true
            annotations_path: brief
            merge_init_into_class: True

theme: readthedocs

nav:
  - README: README.md
  - Reference: reference/
